# -*- coding: utf-8 -*-
"""
/***************************************************************************
 recLayerAdd
                                 A QGIS plugin
 Add a folder in QGIS. It will clone the folder structures and add recursively files throught folders
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-20
        copyright            : (C) 2022 by Vincent Bénet
        email                : vincent.benet@outlook.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load recLayerAdd class from file recLayerAdd.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .recLayerAdd import recLayerAdd
    return recLayerAdd(iface)
